Задание № 1. Ёров Собир, СПбАУ SE 6 курс
h31/NetworksLab2018AU pull request #1
Opened 2018-03-12 16:39 UTC by YorovSobir

Прикладной протокол находится в README.

2018-04-04 11:55 UTC, h31 requested changes

2018-04-04 11:55 UTC, h31 commented on README.md
> +* Для каждого очередного клиента сервер создаёт два потока, что позволяет работать одновременно с несколькими клиентами:
Это не протокол, это описание к вашей программе (к конкретной реализации протокола). Хорошо, что вы умеете писать документацию к программам, но нужно также уметь разделать документы по секциям и выбирать для них подходящие имена.

2018-04-04 11:55 UTC, h31 commented on README.md
> +* Перед отправкой очередного сообщения клиент сначала записывает длину сообщения а потом само сообщение, что позволяет не ограничивать размер сообщений (максимальная длина = **UINT32_MAX**)
А что насчет даты, отправителя? Как клиент сообщает эту информацию серверу?

2018-04-04 11:55 UTC, h31 commented on client/client_linux/handlers.c
> +    bzero(msg->data, msg->capacity);
Для выделения памяти с обнулением есть функция `calloc`.

2018-04-04 11:55 UTC, h31 commented on client/client_linux/handlers.c
> +    while (ch != '\n') {
Для этого есть готовые функции, не обязательно писать самому. Кроме того, у вас не предусмотрен вариант с EOF (когда пользователь отключается и поток ввода больше не работает).

2018-04-04 11:55 UTC, h31 commented on client/client_linux/handlers.c
> +                if (n < 0) {
Форматирование.

2018-04-04 11:55 UTC, h31 commented on client/client_linux/handlers.c
> +            int sockfd = client->sockfd;
Опять форматирование.

2018-04-04 11:55 UTC, h31 commented on client/client_linux/utils.c
> +                strncpy(*server_addr, optarg, len);
Лучше `strlcpy`.

2018-04-04 11:55 UTC, h31 commented on common/linux_common/vector.h
> +        char* temp = malloc(sizeof(char) * (msg->size) * 2);
`realloc`?

2018-04-04 11:55 UTC, h31 commented on server/server_linux/handlers.c
> +            pthread_mutex_unlock(&client->mutex);
Это нормально, что если `n < 0`, то мьютекс не разблокируется?

2018-04-04 11:55 UTC, h31 commented on client/client_windows/handlers.c
> +		if (n < 0) {
Форматирование. И не только здесь. Пройдитесь по файлам, воспользуйтесь IDE с автоформатированием или `clang-format`.

2018-04-04 11:55 UTC, h31 commented on server/server_linux/handlers.c
> +                            continue;
Почему не `break`? Если accept будет всегда выдавать отрицательные значения, то программа зациклится.

2018-04-04 11:57 UTC, h31 commented on common/windows_common/vector.h
> +    uint32_t size;
На самом деле довольно мало смысла в этом поле, потому что большинство функций работает с null-terminated строками и не сможет воспользоваться этим полем.

2018-04-04 12:23 UTC, YorovSobir commented on client/client_linux/handlers.c
> +                if (n < 0) {
Так как `pthread_cleanup_push` - это макрос, то CLion сам так форматирует.

2018-04-04 12:23 UTC, YorovSobir commented on client/client_linux/handlers.c
> +            int sockfd = client->sockfd;
CLion так форматирует макросы.

2018-04-04 12:28 UTC, YorovSobir commented on server/server_linux/handlers.c
> +            pthread_mutex_unlock(&client->mutex);
`pthread_exit` выполняет все зарегистрированные обработчики (то что зарегистрировали с помощью pthread_cleanup_push). [См. pthread_exit](http://man7.org/linux/man-pages/man3/pthread_exit.3.html)

2018-04-04 12:29 UTC, h31 commented on server/server_linux/handlers.c
> +            pthread_mutex_unlock(&client->mutex);
Да, вижу. Не заметил регистрацию обработчика, прошу прощения.

2018-04-04 12:30 UTC, h31 commented on client/client_linux/handlers.c
> +                if (n < 0) {
Всё равно нужно разобраться с этим вопросом. Либо написать багрепорт, либо придумать workaround. Потому что так читать код очень сложно.

2018-05-05 12:49 UTC, YorovSobir commented on README.md
> +* Перед отправкой очередного сообщения клиент сначала записывает длину сообщения а потом само сообщение, что позволяет не ограничивать размер сообщений (максимальная длина = **UINT32_MAX**)
когда сервер получит сообщение от клиента, он сам запишет время перед сообщением и отправит остальным клиентам.

2018-05-05 13:29 UTC, YorovSobir commented on client/client_linux/handlers.c
> +    while (ch != '\n') {
Исправил. Читаю теперь через getline.

2018-05-05 13:33 UTC, YorovSobir commented on client/client_linux/handlers.c
> +    bzero(msg->data, msg->capacity);
Исправил.

2018-05-05 13:37 UTC, YorovSobir commented on client/client_linux/utils.c
> +                strncpy(*server_addr, optarg, len);
этой функции нет уже в <string.h>.

2018-05-05 13:43 UTC, YorovSobir commented on common/linux_common/vector.h
> +        char* temp = malloc(sizeof(char) * (msg->size) * 2);
Исправил

2018-05-05 13:43 UTC, YorovSobir commented on server/server_linux/handlers.c
> +                            continue;
Исправил

2018-05-05 13:46 UTC, YorovSobir commented on common/windows_common/vector.h
> +    uint32_t size;
В методе append, я же должен как - то узнать количество символов. Этот size имеет тотже значение, что size в обычном векторе.

2018-05-05 13:57 UTC, YorovSobir commented on README.md
> +* Для каждого очередного клиента сервер создаёт два потока, что позволяет работать одновременно с несколькими клиентами:
Тогда непонятно что писать в качестве протокола, если не то как я реализовал. Получается протоколом является, то что Вы описали на sewiki.

2018-05-05 13:57 UTC, YorovSobir commented on client/client_windows/handlers.c
> +		if (n < 0) {
Исправил

2018-05-14 16:35 UTC, h31 commented on README.md
> +* Для каждого очередного клиента сервер создаёт два потока, что позволяет работать одновременно с несколькими клиентами:
В качестве описания протокола хочется увидеть что-то похожее на [такое](https://ru.wikipedia.org/wiki/HTTP#%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%B0). То есть суть в том, что описывается не сама программа, а формат обмениваемых данных.

Естественно, по этой ссылке упрощенное описание, но большего я и не требую. Полноценная [спецификация](https://tools.ietf.org/html/rfc7230#section-3) занимает много страниц и пишется в особом стиле.

2018-05-14 16:37 UTC, h31 commented on README.md
> +* Для каждого очередного клиента сервер создаёт два потока, что позволяет работать одновременно с несколькими клиентами:
К кому у меня вопросов нет, всё сделано качественно. То есть осталось только исправить описание протокола.

2018-05-14 16:37 UTC, h31 approved these changes

2018-05-16 11:10 UTC, YorovSobir commented on README.md
> +* Для каждого очередного клиента сервер создаёт два потока, что позволяет работать одновременно с несколькими клиентами:
Исправил описание протокола.

2018-05-22 00:04 UTC, YorovSobir commented
@h31 поменял прикладной протокол.

2018-05-22 13:49 UTC, h31 commented
Ок, принимаю.

2018-05-22 13:49 UTC, closed without merging