Lab01, Иван Веселов
h31/NetworksLab2018AU pull request #2
Opened 2018-03-13 21:40 UTC by Ivan-Veselov

2018-03-20 16:21 UTC, h31 requested changes
Всё хорошо, всё правильно и аккуратно.

2018-03-20 16:21 UTC, h31 commented on messenger/common/communication.c
> +	ssize_t bytes_written1 = send_uint16(sock, length);
Лучше в имени переменной явно указывать, что именно мы отправляем. Например, `bytes_written_time`.

2018-03-20 16:21 UTC, h31 commented on messenger/common/communication.c
> +	size_t length = strlen(string);
`strnlen`.

2018-03-20 16:21 UTC, h31 commented on messenger/common/communication.c
> +ssize_t receive_cstring(int sock, char *string) {
Название немного вводит в заблуждение. Под CString обычно понимается null-terminated строка. А у нас строка с явным указанием длины. Мелочь, конечно, но функции обычно называются по имени сообщений, а не по имени структур данных, куда мы "распаковываем" принятые данные.

2018-03-20 16:21 UTC, h31 commented on messenger/README.md
> +Сервер рассылает клиентам сообщения в следующем формате: часы [2 байта], минуты [2 байта], никнейм [строка], сообщение [строка].
2 байта взяли, потому что уже написали функцию? :)
Всё нормально, можно не исправлять.

2018-03-20 16:21 UTC, h31 commented on messenger/README.md
> +# Описание протокола
Желательно указывать в протоколе максимальный размер сообщения. Сейчас он у вас равен `MAX_CHUNK_LEN`, т.е. 1000 байт.

2018-03-20 16:21 UTC, h31 commented on messenger/common/network.c
> +    #ifndef _WIN32
Да, всё правильно. Или использовать MSG_NOSIGNAL, но такой вариант менее кроссплатформенный.

2018-03-20 16:21 UTC, h31 approved these changes

2018-05-14 16:23 UTC, closed without merging

2018-05-14 18:16 UTC, Ivan-Veselov commented
Это означает, что задание принято?

2018-05-14 18:20 UTC, h31 commented
Да, ваше задание принято. Замечания остались, но я решил, что они несущественны.