HW01, Messenger, Кравцун Андрей.
h31/NetworksLab2018AU pull request #5
Opened 2018-03-17 04:20 UTC by kravtsun

2018-04-04 12:13 UTC, h31 requested changes
Ещё не всё успел посмотреть

2018-04-04 12:13 UTC, h31 commented on messenger/FORMAT.md
> +- строка даты, представляет собой число в формате длинной арифметики (каждому символу соответствует код от 0 до 127, обозначающий цифру в 128-меричной системе счисления) с основанием 128. Массив длин
Не очень понял, зачем нужны такие хитрости. Есть unix time, например. Если у вас передается каждый компонент даты как отдельное число, то хочется видеть формат передачи.

2018-04-04 12:13 UTC, h31 commented on messenger/FORMAT.md
> +- строка имени пользователя;
А как сервер узнает имя пользователя, который отправил сообщение?

2018-04-04 12:13 UTC, h31 commented on messenger/windows_client/main.cpp
> +static SocketWrapper clientSocket;
Где-то имена в стиле snake_case, где-то - в camelCase. Выберите один стиль именования переменных.

2018-04-07 02:36 UTC, kravtsun commented on messenger/FORMAT.md
> +- строка даты, представляет собой число в формате длинной арифметики (каждому символу соответствует код от 0 до 127, обозначающий цифру в 128-меричной системе счисления) с основанием 128. Массив длин
Пояснил.

2018-04-07 02:36 UTC, kravtsun commented on messenger/FORMAT.md
> +- строка имени пользователя;
в сообщении INIT_FROM_CLIENT.

2018-04-07 02:37 UTC, kravtsun commented on messenger/windows_client/main.cpp
> +static SocketWrapper clientSocket;
Выбрал snake_case, прошу прощения, если где-то пропустил.

2018-04-07 02:41 UTC, kravtsun commented
@h31

2018-05-14 17:03 UTC, h31 commented
Не могу собрать ваш код.
```
user@students:~/NetworksLab2018AU/messenger/linux_server# cmake .
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/NetworksLab2018AU/messenger/linux_server
user@students1804:~/NetworksLab2018AU/messenger/linux_server# make
Scanning dependencies of target server_linux
[ 50%] Building CXX object CMakeFiles/server_linux.dir/main.cpp.o
/home/user/NetworksLab2018AU/messenger/linux_server/main.cpp:14:10: fatal error: elegram_all.h: No such file or directory
 #include "elegram_all.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/server_linux.dir/build.make:62: recipe for target 'CMakeFiles/server_linux.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/server_linux.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/server_linux.dir/all' failed
make[1]: *** [CMakeFiles/server_linux.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

2018-05-14 19:33 UTC, kravtsun commented
@h31 Я добавил [README](https://github.com/kravtsun/NetworksLab2018AU/blob/messenger/messenger/README.md) - дело в том, что у меня cmake работает из папки `NetworksLab2018AU/messenger`. Таким образом, можно с одной командой `cmake . && make` скомпилировать оба проекта.

2018-05-19 15:43 UTC, kravtsun commented
@h31

2018-05-22 13:46 UTC, h31 commented
Да, прошу прощения, не заметил. Всё работает, принимаю.

2018-05-22 13:46 UTC, closed without merging