Hw01, messenger, Жидков Николай
h31/NetworksLab2018AU pull request #6
Opened 2018-03-18 11:45 UTC by ZhNV2

2018-04-04 12:19 UTC, h31 requested changes

2018-04-04 12:19 UTC, h31 commented on messenger/linux_client/main.c
> +    int n = read(sockfd, buffer, len);
А если `read` вернет не всю посылку, а только часть?

2018-04-04 12:19 UTC, h31 commented on messenger/linux_client/main.c
> +        memcpy(&hours, header, 1);
Либо просто использовать присваивание. Так будет чуть проще, но по сути разницы никакой, так что можно оставить.

2018-04-04 12:19 UTC, h31 commented on messenger/linux_client/main.c
> +        while (print_pause) {}
Это нормально, что цикл будет крутиться до бесконечности и грузить CPU, пока не снимем флаг `print_pause`? Может, есть какие-нибудь более оптимальные способы приостановить поток или вывод?

2018-04-04 12:19 UTC, h31 commented on messenger/windows_client/main.c
> +    int iResult = send(sockfd, buffer, strlen(buffer), 0);
Где-то имена в стиле snake_case, где-то - в camelCase. Выберите один стиль именования переменных.

2018-04-25 13:29 UTC, ZhNV2 commented on messenger/windows_client/main.c
> +    int iResult = send(sockfd, buffer, strlen(buffer), 0);
исправил

2018-04-25 13:31 UTC, ZhNV2 commented on messenger/linux_client/main.c
> +        memcpy(&hours, header, 1);
в смысле использовать присваивание в первой строчке?
тогда это будет смотреться некрасиво

2018-04-28 20:26 UTC, ZhNV2 commented on messenger/linux_client/main.c
> +        while (print_pause) {}
Добавил слипов

2018-04-29 14:45 UTC, ZhNV2 commented on messenger/linux_client/main.c
> +    int n = read(sockfd, buffer, len);
исправил

2018-04-29 14:46 UTC, ZhNV2 commented
@h31 Все замечания поправил

2018-05-14 16:48 UTC, h31 commented
Всё работает, принимаю. Описание протокола стоило сделать более формальным и подробным (например, как [здесь](https://ru.wikipedia.org/wiki/HTTP#%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%B0)), но основные вещи в нем описаны, и это меня устраивает.

2018-05-14 16:48 UTC, closed without merging